<?php

namespace MySQLndUhTool\Event;

/**
 * Test class for Close.
 * Generated by PHPUnit on 2011-09-15 at 09:45:07.
 */
class CloseTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Close
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = $this->getMockBuilder('MySQLndUhTool\Event\Close')
             ->disableOriginalConstructor()
             ->setMethods(array('__construct'))
             ->getMock();
    }

    public function testCloseType() {
        $this->assertEquals(null, $this->object->getCloseType());
        $this->object->setCloseType(2);
        $this->assertAttributeEquals(2, 'closeType', $this->object);
        $this->assertEquals(2, $this->object->getCloseType());
    }
}