<?php

namespace MySQLndUhTool\Event;

require_once dirname(__FILE__) . '/../../../../src/MySQLndUhTool/Event/Query.php';

/**
 * Test class for Query.
 * Generated by PHPUnit on 2011-09-15 at 10:10:40.
 */
class QueryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Query
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = $this->getMockBuilder('MySQLndUhTool\Event\Query')
             ->disableOriginalConstructor()
             ->setMethods(array('__construct'))
             ->getMock();
    }

    public function testQuery() {
        $this->assertEquals(null, $this->object->getQuery());
        $this->object->setQuery('SELECT * FROM table');
        $this->assertAttributeEquals('SELECT * FROM table', 'query', $this->object);
        $this->assertEquals('SELECT * FROM table', $this->object->getQuery());
    }

    public function testTime() {
        $this->assertEquals(null, $this->object->getTime());
        $this->object->setTime(0.2);
        $this->assertAttributeEquals(0.2, 'time', $this->object);
        $this->assertEquals(0.2, $this->object->getTime());
    }
}