<?php

namespace MySQLndUhTool;

/**
 * Test class for CloseEvents.
 * Generated by PHPUnit on 2011-09-15 at 10:21:18.
 */
class CloseEventsTest extends \PHPUnit_Framework_TestCase {

    public function testConstants() {
        $this->assertStringStartsWith('close', CloseEvents::PRE_CLOSE);
        $this->assertStringStartsWith('close', CloseEvents::POST_CLOSE);
        $this->assertNotEquals(CloseEvents::PRE_CLOSE, CloseEvents::POST_CLOSE);
    }

}