<?php

namespace MySQLndUhTool;

/**
 * Test class for ConnectEvents.
 * Generated by PHPUnit on 2011-09-15 at 10:21:18.
 */
class ConnectEventsTest extends \PHPUnit_Framework_TestCase {

    public function testConstants() {
        $this->assertStringStartsWith('connect', ConnectEvents::PRE_CONNECT);
        $this->assertStringStartsWith('connect', ConnectEvents::POST_CONNECT);
        $this->assertStringStartsWith('connect', ConnectEvents::FAIL);
        $this->assertNotEquals(ConnectEvents::PRE_CONNECT, ConnectEvents::POST_CONNECT);
        $this->assertNotEquals(ConnectEvents::PRE_CONNECT, ConnectEvents::FAIL);
    }

}