<?php

namespace MySQLndUhTool;

/**
 * Test class for QueryEvents.
 * Generated by PHPUnit on 2011-09-15 at 10:21:19.
 */
class QueryEventsTest extends \PHPUnit_Framework_TestCase {

    public function testConstants() {
        $this->assertStringStartsWith('query', QueryEvents::PRE_EXECUTION);
        $this->assertStringStartsWith('query', QueryEvents::POST_EXECUTION);
        $this->assertStringStartsWith('query', QueryEvents::SLOW);
        $this->assertStringStartsWith('query', QueryEvents::DUPLICATE);
        $this->assertStringStartsWith('query', QueryEvents::FAIL);
        $this->assertNotEquals(QueryEvents::PRE_EXECUTION, QueryEvents::POST_EXECUTION);
        $this->assertNotEquals(QueryEvents::SLOW, QueryEvents::DUPLICATE);
        $this->assertNotEquals(QueryEvents::SLOW, QueryEvents::FAIL);
    }

}